language: objective-c

osx_image: xcode611

before_install:
  - gem install xcpretty

script:
  - xcodebuild -scheme Gonzales-OSX -sdk macosx10.10 clean test | xcpretty -c
  - xcodebuild -scheme Gonzales-iOS -sdk iphonesimulator clean test | xcpretty -c